---
- hosts:
    - '127.0.0.1'

  tasks:
    - name: Link vimrc
      args:
        chdir: ..
        creates: $HOME/.vimrc
      ansible.builtin.shell: |
        ln -sv `pwd`/.vimrc $HOME/.vimrc

    - name: Create IDEA vimrc
      args:
        creates: $HOME/.ideavimrc
      ansible.builtin.shell: |
        cp $HOME/.dotfiles/.vimrc $HOME/.ideavimrc
        # Disable intellij bell
        echo "set visualbell" >> $HOME/.ideavimrc

    - name: Install sdkman
      args:
        warn: false # otherwise will warn against using curl
        creates: $HOME/.sdkman/bin/sdkman-init.sh
      ansible.builtin.shell: |
        curl -s "https://get.sdkman.io" | bash

    # rip jonathonf
    #- name: Add vim repository
    #  become: yes
    #  become_method: sudo
    #  ansible.builtin.apt_repository:
    #    repo: ppa:jonathonf/vim
    #    state: present

    # If this does not work due to problems with python-apt,
    # use -e ansible_python_interpreter=/usr/bin/python3
    - name: Install apt packages
      become: yes
      become_method: sudo
      apt:
        pkg:
          - tmux
          - htop
          - tree
          - jq
          - python-is-python3
          - gnome-tweaks
          - gnome-shell-extensions
            # TODO: add vim. need to condition this on vim repo successfully added
