---
- hosts:
    - '127.0.0.1'

  vars:
    apt_packages:
      - curl
      - zip
      - tmux
      - htop
      - tree
      - jq
      - python-is-python3
      - gnome-tweaks
      - gnome-shell-extensions
      - vim
      - git
      - gh

  tasks:
    - name: Update, upgrade and autoremove packages
      become: yes
      become_method: sudo
      apt:
        update_cache: true
        upgrade: yes
        autoremove: true

    # If this does not work due to problems with python-apt,
    # use -e ansible_python_interpreter=/usr/bin/python3
    - name: Install apt packages
      become: yes
      become_method: sudo
      apt:
        pkg: "{{ apt_packages }}"

    - name: Link vimrc
      args:
        chdir: ..
        creates: $HOME/.vimrc
      ansible.builtin.shell: |
        ln -sv `pwd`/.vimrc $HOME/.vimrc

    - name: Create IDEA vimrc
      args:
        creates: $HOME/.ideavimrc
      ansible.builtin.shell: |
        cp $HOME/.dotfiles/.vimrc $HOME/.ideavimrc
        # Disable intellij bell
        echo "set visualbell" >> $HOME/.ideavimrc

    - name: Link tmux conf
      args:
        chdir: ..
        creates: $HOME/.tmux.conf
      ansible.builtin.shell: |
        ln -sv `pwd`/.tmux.conf $HOME/.tmux.conf

    - name: Source tobashrc
      ansible.builtin.lineinfile:
        path: $HOME/.bashrc
        line: source $HOME/.dotfiles/.tobashrc
        state: present

    - name: Install sdkman
      args:
        creates: $HOME/.sdkman/bin/sdkman-init.sh
      ansible.builtin.shell: |
        curl -s "https://get.sdkman.io" | bash

    - name: Install sbt
      args:
        creates: $HOME/.sdkman/candidates/sbt/
        executable: /bin/bash
      ansible.builtin.shell: |
        . ~/.sdkman/bin/sdkman-init.sh
        sdk install sbt

    - name: Install mvn
      args:
        creates: $HOME/.sdkman/candidates/maven/
        executable: /bin/bash
      ansible.builtin.shell: |
        . ~/.sdkman/bin/sdkman-init.sh
        sdk install maven 3.8.8

    # rip jonathonf
    #- name: Add vim repository
    #  become: yes
    #  become_method: sudo
    #  ansible.builtin.apt_repository:
    #    repo: ppa:jonathonf/vim
    #    state: present

    # TODO:
    # install java and scala
    # nvm
    # set up git
    # set up gh (github cli)
    # install intellij
